const splashTextOptions = [
    "The world's <i>most</i> website",
    "One of the websites of all time",
    "\"Its the best\" -Kaden Emrich",
    "By: Kaden Emrich",
    "Always be flexin'",
    "[insert-funny-subheading-here]",
    "A website",
    "BUBBLES!!!",
    "Better than Google!",
    "No login required",
    "We have game(s)!",
    "kaden wuz heree",
    "3p1c l33t w3bs1t3",
    "It's hiding <a href=\"../secret\">something</a>",
    "NO SOLICITING",
    "We like to have fun around here",
    "There may be speling errors",
    "Live from New York",
    "help.",
    "please don't play <a href=\"https://clicker-clicker.kadenemrich.com\">clicker-clicker</a>",
    "No, I am your father!",
    "Procrastinating everything since 2006",
    "Where do you think you're going?",
    "I've been expecting you",
    "there is no escape",
    "No viruses I promise",
    "Monospace is the best font",
    "Refresh for a more creative subtitle",
    "I try",
    "Where it's at",
    "Now in blue!",
    "How much caffeine is too much caffeine?",
    "Can't sleep?",
    "wake up.",
    "(not clickbait)",
    "Est. 2023",
    "Start taking notes",
    "Home of The Kaden",
    "Get off your phone and go outside",
    "Take it back now yall",
    "GET BACK TO WORK",
    "Heavy is dead!",
    "OUTATIME",
    "Let's get down to business",
    "How did you get here?",
    "Why have you come to this forsaken place?",
    "You shall not pass",
    "Get outa here kid",
    "Where dreams come true",
    "= 42"
];

function pickSplashText() {
    var selection = splashTextOptions[Math.floor(Math.random() * splashTextOptions.length)];

    document.getElementById("splash-text").innerHTML = selection;
}

pickSplashText();