const splashTextOptions = [
    "The world's <i>most</i> website",
    "One of the websites of all time",
    "\"Its the best\" -Kaden Emrich",
    "By: Kaden Emrich",
    "Always be flexin'",
    "[insert-funny-subtitle-here]",
    "A website",
    "BUBBLES!!!",
    "Better than Google!",
    "No login required",
    "We have game(s)!",
    "kaden wuz heree",
    "3p1c l33t w3bs1t3",
    "There are <a href=\"../secret\">secrets</a>",
    "NO SOLICITING",
    "We like to have fun around here",
    "There are probably speling errors",
    "Free as a bird",
    "help.",
    "<a href=\"https://clickthebutton.kadenemrich.com\">click</a>",
    "Also try Minecraft!",
    "Procrastinating everything since 2006",
    "my dad thinks my website is cool",
    "I've been expecting you",
    "there is no escape",
    "No viruses I promise",
    "Monospace is the best font",
    "Refresh for a more creative subtitle",
    "I try",
    "Where it's at",
    "Now in blue!",
    "How much caffeine is too much caffeine?",
    "wake up.",
    "(not clickbait)",
    "Est. 2023",
    "Start taking notes",
    "Home of the original <i>The Kaden</i>",
    "Get off your phone and go outside",
    "Take it back now yall",
    "GET BACK TO WORK",
    "Beep Beep Boop",
    "OUTATIME",
    "Let's get down to business",
    "How did you get here?",
    "Never gonna give you up...",
    "You shall not pass",
    "kadenemrich.com",
    "Where dreams come true",
    "= 42",
    "Welcome to Paradise"
];

function pickSplashText() {
    var selection = splashTextOptions[Math.floor(Math.random() * splashTextOptions.length)];

    document.getElementById("splash-text").innerHTML = selection;
}

pickSplashText();